<?php
/**
 * RequestWhitelistEntry
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Distributor PPU Service
 *
 * © KnowRoaming LTD 2017
 *
 * OpenAPI spec version: v1.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.35
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace Swagger\Client\Model;

use \ArrayAccess;
use \Swagger\Client\ObjectSerializer;

/**
 * RequestWhitelistEntry Class Doc Comment
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class RequestWhitelistEntry implements ModelInterface, ArrayAccess
{
    const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $swaggerModelName = 'RequestWhitelistEntry';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $swaggerTypes = [
        'country_iso3' => 'string',
'sponsor_imsi_id' => 'int',
'network_id' => 'int',
'new_voice_status' => 'string',
'new_sms_status' => 'string',
'new_data_status' => 'string'    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $swaggerFormats = [
        'country_iso3' => null,
'sponsor_imsi_id' => 'int32',
'network_id' => 'int32',
'new_voice_status' => null,
'new_sms_status' => null,
'new_data_status' => null    ];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function swaggerTypes()
    {
        return self::$swaggerTypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function swaggerFormats()
    {
        return self::$swaggerFormats;
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'country_iso3' => 'countryIso3',
'sponsor_imsi_id' => 'sponsorImsiId',
'network_id' => 'networkId',
'new_voice_status' => 'newVoiceStatus',
'new_sms_status' => 'newSmsStatus',
'new_data_status' => 'newDataStatus'    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'country_iso3' => 'setCountryIso3',
'sponsor_imsi_id' => 'setSponsorImsiId',
'network_id' => 'setNetworkId',
'new_voice_status' => 'setNewVoiceStatus',
'new_sms_status' => 'setNewSmsStatus',
'new_data_status' => 'setNewDataStatus'    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'country_iso3' => 'getCountryIso3',
'sponsor_imsi_id' => 'getSponsorImsiId',
'network_id' => 'getNetworkId',
'new_voice_status' => 'getNewVoiceStatus',
'new_sms_status' => 'getNewSmsStatus',
'new_data_status' => 'getNewDataStatus'    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$swaggerModelName;
    }

    const NEW_VOICE_STATUS_DIRECT = 'DIRECT';
const NEW_VOICE_STATUS_CALLBACK = 'CALLBACK';
const NEW_VOICE_STATUS_PILOT = 'PILOT';
const NEW_VOICE_STATUS_BLOCKED = 'BLOCKED';
const NEW_SMS_STATUS_ALLOWED = 'ALLOWED';
const NEW_SMS_STATUS_BLOCKED = 'BLOCKED';
const NEW_DATA_STATUS_ALLOWED = 'ALLOWED';
const NEW_DATA_STATUS_BLOCKED = 'BLOCKED';

    /**
     * Gets allowable values of the enum
     *
     * @return string[]
     */
    public function getNewVoiceStatusAllowableValues()
    {
        return [
            self::NEW_VOICE_STATUS_DIRECT,
self::NEW_VOICE_STATUS_CALLBACK,
self::NEW_VOICE_STATUS_PILOT,
self::NEW_VOICE_STATUS_BLOCKED,        ];
    }
    /**
     * Gets allowable values of the enum
     *
     * @return string[]
     */
    public function getNewSmsStatusAllowableValues()
    {
        return [
            self::NEW_SMS_STATUS_ALLOWED,
self::NEW_SMS_STATUS_BLOCKED,        ];
    }
    /**
     * Gets allowable values of the enum
     *
     * @return string[]
     */
    public function getNewDataStatusAllowableValues()
    {
        return [
            self::NEW_DATA_STATUS_ALLOWED,
self::NEW_DATA_STATUS_BLOCKED,        ];
    }

    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[] $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->container['country_iso3'] = isset($data['country_iso3']) ? $data['country_iso3'] : null;
        $this->container['sponsor_imsi_id'] = isset($data['sponsor_imsi_id']) ? $data['sponsor_imsi_id'] : null;
        $this->container['network_id'] = isset($data['network_id']) ? $data['network_id'] : null;
        $this->container['new_voice_status'] = isset($data['new_voice_status']) ? $data['new_voice_status'] : null;
        $this->container['new_sms_status'] = isset($data['new_sms_status']) ? $data['new_sms_status'] : null;
        $this->container['new_data_status'] = isset($data['new_data_status']) ? $data['new_data_status'] : null;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        if ($this->container['country_iso3'] === null) {
            $invalidProperties[] = "'country_iso3' can't be null";
        }
        if ($this->container['sponsor_imsi_id'] === null) {
            $invalidProperties[] = "'sponsor_imsi_id' can't be null";
        }
        if ($this->container['network_id'] === null) {
            $invalidProperties[] = "'network_id' can't be null";
        }
        $allowedValues = $this->getNewVoiceStatusAllowableValues();
        if (!is_null($this->container['new_voice_status']) && !in_array($this->container['new_voice_status'], $allowedValues, true)) {
            $invalidProperties[] = sprintf(
                "invalid value for 'new_voice_status', must be one of '%s'",
                implode("', '", $allowedValues)
            );
        }

        $allowedValues = $this->getNewSmsStatusAllowableValues();
        if (!is_null($this->container['new_sms_status']) && !in_array($this->container['new_sms_status'], $allowedValues, true)) {
            $invalidProperties[] = sprintf(
                "invalid value for 'new_sms_status', must be one of '%s'",
                implode("', '", $allowedValues)
            );
        }

        $allowedValues = $this->getNewDataStatusAllowableValues();
        if (!is_null($this->container['new_data_status']) && !in_array($this->container['new_data_status'], $allowedValues, true)) {
            $invalidProperties[] = sprintf(
                "invalid value for 'new_data_status', must be one of '%s'",
                implode("', '", $allowedValues)
            );
        }

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets country_iso3
     *
     * @return string
     */
    public function getCountryIso3()
    {
        return $this->container['country_iso3'];
    }

    /**
     * Sets country_iso3
     *
     * @param string $country_iso3 The country iso3
     *
     * @return $this
     */
    public function setCountryIso3($country_iso3)
    {
        $this->container['country_iso3'] = $country_iso3;

        return $this;
    }

    /**
     * Gets sponsor_imsi_id
     *
     * @return int
     */
    public function getSponsorImsiId()
    {
        return $this->container['sponsor_imsi_id'];
    }

    /**
     * Sets sponsor_imsi_id
     *
     * @param int $sponsor_imsi_id The sponsored IMSI id
     *
     * @return $this
     */
    public function setSponsorImsiId($sponsor_imsi_id)
    {
        $this->container['sponsor_imsi_id'] = $sponsor_imsi_id;

        return $this;
    }

    /**
     * Gets network_id
     *
     * @return int
     */
    public function getNetworkId()
    {
        return $this->container['network_id'];
    }

    /**
     * Sets network_id
     *
     * @param int $network_id The network id
     *
     * @return $this
     */
    public function setNetworkId($network_id)
    {
        $this->container['network_id'] = $network_id;

        return $this;
    }

    /**
     * Gets new_voice_status
     *
     * @return string
     */
    public function getNewVoiceStatus()
    {
        return $this->container['new_voice_status'];
    }

    /**
     * Sets new_voice_status
     *
     * @param string $new_voice_status The new voice status
     *
     * @return $this
     */
    public function setNewVoiceStatus($new_voice_status)
    {
        $allowedValues = $this->getNewVoiceStatusAllowableValues();
        if (!is_null($new_voice_status) && !in_array($new_voice_status, $allowedValues, true)) {
            throw new \InvalidArgumentException(
                sprintf(
                    "Invalid value for 'new_voice_status', must be one of '%s'",
                    implode("', '", $allowedValues)
                )
            );
        }
        $this->container['new_voice_status'] = $new_voice_status;

        return $this;
    }

    /**
     * Gets new_sms_status
     *
     * @return string
     */
    public function getNewSmsStatus()
    {
        return $this->container['new_sms_status'];
    }

    /**
     * Sets new_sms_status
     *
     * @param string $new_sms_status The new sms status
     *
     * @return $this
     */
    public function setNewSmsStatus($new_sms_status)
    {
        $allowedValues = $this->getNewSmsStatusAllowableValues();
        if (!is_null($new_sms_status) && !in_array($new_sms_status, $allowedValues, true)) {
            throw new \InvalidArgumentException(
                sprintf(
                    "Invalid value for 'new_sms_status', must be one of '%s'",
                    implode("', '", $allowedValues)
                )
            );
        }
        $this->container['new_sms_status'] = $new_sms_status;

        return $this;
    }

    /**
     * Gets new_data_status
     *
     * @return string
     */
    public function getNewDataStatus()
    {
        return $this->container['new_data_status'];
    }

    /**
     * Sets new_data_status
     *
     * @param string $new_data_status The new data status
     *
     * @return $this
     */
    public function setNewDataStatus($new_data_status)
    {
        $allowedValues = $this->getNewDataStatusAllowableValues();
        if (!is_null($new_data_status) && !in_array($new_data_status, $allowedValues, true)) {
            throw new \InvalidArgumentException(
                sprintf(
                    "Invalid value for 'new_data_status', must be one of '%s'",
                    implode("', '", $allowedValues)
                )
            );
        }
        $this->container['new_data_status'] = $new_data_status;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    public function offsetExists($offset)
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed
     */
    public function offsetGet($offset)
    {
        return isset($this->container[$offset]) ? $this->container[$offset] : null;
    }

    /**
     * Sets value based on offset.
     *
     * @param integer $offset Offset
     * @param mixed   $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value)
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    public function offsetUnset($offset)
    {
        unset($this->container[$offset]);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        if (defined('JSON_PRETTY_PRINT')) { // use JSON pretty print
            return json_encode(
                ObjectSerializer::sanitizeForSerialization($this),
                JSON_PRETTY_PRINT
            );
        }

        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}
