<?php
/**
 * RequestCreateImsiSlotProfile
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Distributor PPU Service
 *
 * © KnowRoaming LTD 2017
 *
 * OpenAPI spec version: v1.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.35
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace Swagger\Client\Model;

use \ArrayAccess;
use \Swagger\Client\ObjectSerializer;

/**
 * RequestCreateImsiSlotProfile Class Doc Comment
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class RequestCreateImsiSlotProfile implements ModelInterface, ArrayAccess
{
    const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $swaggerModelName = 'RequestCreateImsiSlotProfile';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $swaggerTypes = [
        'imsi_slot_profile_name' => 'string',
'imsi_slot_mapping' => '\Swagger\Client\Model\RequestImsiSlotMapping[]'    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $swaggerFormats = [
        'imsi_slot_profile_name' => null,
'imsi_slot_mapping' => null    ];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function swaggerTypes()
    {
        return self::$swaggerTypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function swaggerFormats()
    {
        return self::$swaggerFormats;
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'imsi_slot_profile_name' => 'imsiSlotProfileName',
'imsi_slot_mapping' => 'imsiSlotMapping'    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'imsi_slot_profile_name' => 'setImsiSlotProfileName',
'imsi_slot_mapping' => 'setImsiSlotMapping'    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'imsi_slot_profile_name' => 'getImsiSlotProfileName',
'imsi_slot_mapping' => 'getImsiSlotMapping'    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$swaggerModelName;
    }

    

    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[] $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->container['imsi_slot_profile_name'] = isset($data['imsi_slot_profile_name']) ? $data['imsi_slot_profile_name'] : null;
        $this->container['imsi_slot_mapping'] = isset($data['imsi_slot_mapping']) ? $data['imsi_slot_mapping'] : null;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        if ($this->container['imsi_slot_profile_name'] === null) {
            $invalidProperties[] = "'imsi_slot_profile_name' can't be null";
        }
        if ($this->container['imsi_slot_mapping'] === null) {
            $invalidProperties[] = "'imsi_slot_mapping' can't be null";
        }
        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets imsi_slot_profile_name
     *
     * @return string
     */
    public function getImsiSlotProfileName()
    {
        return $this->container['imsi_slot_profile_name'];
    }

    /**
     * Sets imsi_slot_profile_name
     *
     * @param string $imsi_slot_profile_name The IMSI Slot Profile Name
     *
     * @return $this
     */
    public function setImsiSlotProfileName($imsi_slot_profile_name)
    {
        $this->container['imsi_slot_profile_name'] = $imsi_slot_profile_name;

        return $this;
    }

    /**
     * Gets imsi_slot_mapping
     *
     * @return \Swagger\Client\Model\RequestImsiSlotMapping[]
     */
    public function getImsiSlotMapping()
    {
        return $this->container['imsi_slot_mapping'];
    }

    /**
     * Sets imsi_slot_mapping
     *
     * @param \Swagger\Client\Model\RequestImsiSlotMapping[] $imsi_slot_mapping The IMSI Slot Mapping
     *
     * @return $this
     */
    public function setImsiSlotMapping($imsi_slot_mapping)
    {
        $this->container['imsi_slot_mapping'] = $imsi_slot_mapping;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    public function offsetExists($offset)
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed
     */
    public function offsetGet($offset)
    {
        return isset($this->container[$offset]) ? $this->container[$offset] : null;
    }

    /**
     * Sets value based on offset.
     *
     * @param integer $offset Offset
     * @param mixed   $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value)
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    public function offsetUnset($offset)
    {
        unset($this->container[$offset]);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        if (defined('JSON_PRETTY_PRINT')) { // use JSON pretty print
            return json_encode(
                ObjectSerializer::sanitizeForSerialization($this),
                JSON_PRETTY_PRINT
            );
        }

        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}
