<?php
/**
 * RequestSimStatus
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Distributor PPU Service
 *
 * © KnowRoaming LTD 2017
 *
 * OpenAPI spec version: v1.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.35
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace Swagger\Client\Model;

use \ArrayAccess;
use \Swagger\Client\ObjectSerializer;

/**
 * RequestSimStatus Class Doc Comment
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class RequestSimStatus implements ModelInterface, ArrayAccess
{
    const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $swaggerModelName = 'RequestSimStatus';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $swaggerTypes = [
        'sim_data_service_status' => 'string',
'sim_voice_service_status' => 'string',
'sim_sms_service_status' => 'string'    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $swaggerFormats = [
        'sim_data_service_status' => null,
'sim_voice_service_status' => null,
'sim_sms_service_status' => null    ];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function swaggerTypes()
    {
        return self::$swaggerTypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function swaggerFormats()
    {
        return self::$swaggerFormats;
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'sim_data_service_status' => 'simDataServiceStatus',
'sim_voice_service_status' => 'simVoiceServiceStatus',
'sim_sms_service_status' => 'simSmsServiceStatus'    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'sim_data_service_status' => 'setSimDataServiceStatus',
'sim_voice_service_status' => 'setSimVoiceServiceStatus',
'sim_sms_service_status' => 'setSimSmsServiceStatus'    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'sim_data_service_status' => 'getSimDataServiceStatus',
'sim_voice_service_status' => 'getSimVoiceServiceStatus',
'sim_sms_service_status' => 'getSimSmsServiceStatus'    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$swaggerModelName;
    }

    const SIM_DATA_SERVICE_STATUS_ENABLED = 'ENABLED';
const SIM_DATA_SERVICE_STATUS_DISABLED = 'DISABLED';
const SIM_VOICE_SERVICE_STATUS_ENABLED = 'ENABLED';
const SIM_VOICE_SERVICE_STATUS_DISABLED = 'DISABLED';
const SIM_SMS_SERVICE_STATUS_ENABLED = 'ENABLED';
const SIM_SMS_SERVICE_STATUS_DISABLED = 'DISABLED';

    /**
     * Gets allowable values of the enum
     *
     * @return string[]
     */
    public function getSimDataServiceStatusAllowableValues()
    {
        return [
            self::SIM_DATA_SERVICE_STATUS_ENABLED,
self::SIM_DATA_SERVICE_STATUS_DISABLED,        ];
    }
    /**
     * Gets allowable values of the enum
     *
     * @return string[]
     */
    public function getSimVoiceServiceStatusAllowableValues()
    {
        return [
            self::SIM_VOICE_SERVICE_STATUS_ENABLED,
self::SIM_VOICE_SERVICE_STATUS_DISABLED,        ];
    }
    /**
     * Gets allowable values of the enum
     *
     * @return string[]
     */
    public function getSimSmsServiceStatusAllowableValues()
    {
        return [
            self::SIM_SMS_SERVICE_STATUS_ENABLED,
self::SIM_SMS_SERVICE_STATUS_DISABLED,        ];
    }

    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[] $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->container['sim_data_service_status'] = isset($data['sim_data_service_status']) ? $data['sim_data_service_status'] : null;
        $this->container['sim_voice_service_status'] = isset($data['sim_voice_service_status']) ? $data['sim_voice_service_status'] : null;
        $this->container['sim_sms_service_status'] = isset($data['sim_sms_service_status']) ? $data['sim_sms_service_status'] : null;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        $allowedValues = $this->getSimDataServiceStatusAllowableValues();
        if (!is_null($this->container['sim_data_service_status']) && !in_array($this->container['sim_data_service_status'], $allowedValues, true)) {
            $invalidProperties[] = sprintf(
                "invalid value for 'sim_data_service_status', must be one of '%s'",
                implode("', '", $allowedValues)
            );
        }

        $allowedValues = $this->getSimVoiceServiceStatusAllowableValues();
        if (!is_null($this->container['sim_voice_service_status']) && !in_array($this->container['sim_voice_service_status'], $allowedValues, true)) {
            $invalidProperties[] = sprintf(
                "invalid value for 'sim_voice_service_status', must be one of '%s'",
                implode("', '", $allowedValues)
            );
        }

        $allowedValues = $this->getSimSmsServiceStatusAllowableValues();
        if (!is_null($this->container['sim_sms_service_status']) && !in_array($this->container['sim_sms_service_status'], $allowedValues, true)) {
            $invalidProperties[] = sprintf(
                "invalid value for 'sim_sms_service_status', must be one of '%s'",
                implode("', '", $allowedValues)
            );
        }

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets sim_data_service_status
     *
     * @return string
     */
    public function getSimDataServiceStatus()
    {
        return $this->container['sim_data_service_status'];
    }

    /**
     * Sets sim_data_service_status
     *
     * @param string $sim_data_service_status The new status of a SIM data service
     *
     * @return $this
     */
    public function setSimDataServiceStatus($sim_data_service_status)
    {
        $allowedValues = $this->getSimDataServiceStatusAllowableValues();
        if (!is_null($sim_data_service_status) && !in_array($sim_data_service_status, $allowedValues, true)) {
            throw new \InvalidArgumentException(
                sprintf(
                    "Invalid value for 'sim_data_service_status', must be one of '%s'",
                    implode("', '", $allowedValues)
                )
            );
        }
        $this->container['sim_data_service_status'] = $sim_data_service_status;

        return $this;
    }

    /**
     * Gets sim_voice_service_status
     *
     * @return string
     */
    public function getSimVoiceServiceStatus()
    {
        return $this->container['sim_voice_service_status'];
    }

    /**
     * Sets sim_voice_service_status
     *
     * @param string $sim_voice_service_status The new status of a SIM voice service
     *
     * @return $this
     */
    public function setSimVoiceServiceStatus($sim_voice_service_status)
    {
        $allowedValues = $this->getSimVoiceServiceStatusAllowableValues();
        if (!is_null($sim_voice_service_status) && !in_array($sim_voice_service_status, $allowedValues, true)) {
            throw new \InvalidArgumentException(
                sprintf(
                    "Invalid value for 'sim_voice_service_status', must be one of '%s'",
                    implode("', '", $allowedValues)
                )
            );
        }
        $this->container['sim_voice_service_status'] = $sim_voice_service_status;

        return $this;
    }

    /**
     * Gets sim_sms_service_status
     *
     * @return string
     */
    public function getSimSmsServiceStatus()
    {
        return $this->container['sim_sms_service_status'];
    }

    /**
     * Sets sim_sms_service_status
     *
     * @param string $sim_sms_service_status The new status of a SIM SMS service
     *
     * @return $this
     */
    public function setSimSmsServiceStatus($sim_sms_service_status)
    {
        $allowedValues = $this->getSimSmsServiceStatusAllowableValues();
        if (!is_null($sim_sms_service_status) && !in_array($sim_sms_service_status, $allowedValues, true)) {
            throw new \InvalidArgumentException(
                sprintf(
                    "Invalid value for 'sim_sms_service_status', must be one of '%s'",
                    implode("', '", $allowedValues)
                )
            );
        }
        $this->container['sim_sms_service_status'] = $sim_sms_service_status;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    public function offsetExists($offset)
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed
     */
    public function offsetGet($offset)
    {
        return isset($this->container[$offset]) ? $this->container[$offset] : null;
    }

    /**
     * Sets value based on offset.
     *
     * @param integer $offset Offset
     * @param mixed   $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value)
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    public function offsetUnset($offset)
    {
        unset($this->container[$offset]);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        if (defined('JSON_PRETTY_PRINT')) { // use JSON pretty print
            return json_encode(
                ObjectSerializer::sanitizeForSerialization($this),
                JSON_PRETTY_PRINT
            );
        }

        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}
