<?php
/**
 * RequestCreateInventory
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Distributor PPU Service
 *
 * © KnowRoaming LTD 2017
 *
 * OpenAPI spec version: v1.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.35
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace Swagger\Client\Model;

use \ArrayAccess;
use \Swagger\Client\ObjectSerializer;

/**
 * RequestCreateInventory Class Doc Comment
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class RequestCreateInventory implements ModelInterface, ArrayAccess
{
    const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $swaggerModelName = 'RequestCreateInventory';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $swaggerTypes = [
        'name' => 'string',
'parent_inventory_id' => 'int',
'overdraft_in_cents' => 'float',
'overdraft_currency' => 'string',
'balance_in_cents' => 'float',
'balance_currency' => 'string',
'whitelist_name' => 'string',
'type' => 'string'    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $swaggerFormats = [
        'name' => null,
'parent_inventory_id' => 'int32',
'overdraft_in_cents' => null,
'overdraft_currency' => null,
'balance_in_cents' => null,
'balance_currency' => null,
'whitelist_name' => null,
'type' => null    ];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function swaggerTypes()
    {
        return self::$swaggerTypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function swaggerFormats()
    {
        return self::$swaggerFormats;
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'name' => 'name',
'parent_inventory_id' => 'parentInventoryId',
'overdraft_in_cents' => 'overdraftInCents',
'overdraft_currency' => 'overdraftCurrency',
'balance_in_cents' => 'balanceInCents',
'balance_currency' => 'balanceCurrency',
'whitelist_name' => 'whitelistName',
'type' => 'type'    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'name' => 'setName',
'parent_inventory_id' => 'setParentInventoryId',
'overdraft_in_cents' => 'setOverdraftInCents',
'overdraft_currency' => 'setOverdraftCurrency',
'balance_in_cents' => 'setBalanceInCents',
'balance_currency' => 'setBalanceCurrency',
'whitelist_name' => 'setWhitelistName',
'type' => 'setType'    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'name' => 'getName',
'parent_inventory_id' => 'getParentInventoryId',
'overdraft_in_cents' => 'getOverdraftInCents',
'overdraft_currency' => 'getOverdraftCurrency',
'balance_in_cents' => 'getBalanceInCents',
'balance_currency' => 'getBalanceCurrency',
'whitelist_name' => 'getWhitelistName',
'type' => 'getType'    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$swaggerModelName;
    }

    const TYPE_WHOLESALE = 'WHOLESALE';
const TYPE_T4_T = 'T4T';

    /**
     * Gets allowable values of the enum
     *
     * @return string[]
     */
    public function getTypeAllowableValues()
    {
        return [
            self::TYPE_WHOLESALE,
self::TYPE_T4_T,        ];
    }

    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[] $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->container['name'] = isset($data['name']) ? $data['name'] : null;
        $this->container['parent_inventory_id'] = isset($data['parent_inventory_id']) ? $data['parent_inventory_id'] : null;
        $this->container['overdraft_in_cents'] = isset($data['overdraft_in_cents']) ? $data['overdraft_in_cents'] : null;
        $this->container['overdraft_currency'] = isset($data['overdraft_currency']) ? $data['overdraft_currency'] : null;
        $this->container['balance_in_cents'] = isset($data['balance_in_cents']) ? $data['balance_in_cents'] : null;
        $this->container['balance_currency'] = isset($data['balance_currency']) ? $data['balance_currency'] : null;
        $this->container['whitelist_name'] = isset($data['whitelist_name']) ? $data['whitelist_name'] : null;
        $this->container['type'] = isset($data['type']) ? $data['type'] : null;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        if ($this->container['name'] === null) {
            $invalidProperties[] = "'name' can't be null";
        }
        if ($this->container['parent_inventory_id'] === null) {
            $invalidProperties[] = "'parent_inventory_id' can't be null";
        }
        if ($this->container['overdraft_in_cents'] === null) {
            $invalidProperties[] = "'overdraft_in_cents' can't be null";
        }
        if ($this->container['overdraft_currency'] === null) {
            $invalidProperties[] = "'overdraft_currency' can't be null";
        }
        if ($this->container['balance_in_cents'] === null) {
            $invalidProperties[] = "'balance_in_cents' can't be null";
        }
        if ($this->container['balance_currency'] === null) {
            $invalidProperties[] = "'balance_currency' can't be null";
        }
        if ($this->container['whitelist_name'] === null) {
            $invalidProperties[] = "'whitelist_name' can't be null";
        }
        $allowedValues = $this->getTypeAllowableValues();
        if (!is_null($this->container['type']) && !in_array($this->container['type'], $allowedValues, true)) {
            $invalidProperties[] = sprintf(
                "invalid value for 'type', must be one of '%s'",
                implode("', '", $allowedValues)
            );
        }

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets name
     *
     * @return string
     */
    public function getName()
    {
        return $this->container['name'];
    }

    /**
     * Sets name
     *
     * @param string $name The name the Inventory to be created
     *
     * @return $this
     */
    public function setName($name)
    {
        $this->container['name'] = $name;

        return $this;
    }

    /**
     * Gets parent_inventory_id
     *
     * @return int
     */
    public function getParentInventoryId()
    {
        return $this->container['parent_inventory_id'];
    }

    /**
     * Sets parent_inventory_id
     *
     * @param int $parent_inventory_id The Id of the Inventory that the new Inventory should be created under
     *
     * @return $this
     */
    public function setParentInventoryId($parent_inventory_id)
    {
        $this->container['parent_inventory_id'] = $parent_inventory_id;

        return $this;
    }

    /**
     * Gets overdraft_in_cents
     *
     * @return float
     */
    public function getOverdraftInCents()
    {
        return $this->container['overdraft_in_cents'];
    }

    /**
     * Sets overdraft_in_cents
     *
     * @param float $overdraft_in_cents The amount (in cents) that this Inventory's balance can go below 0
     *
     * @return $this
     */
    public function setOverdraftInCents($overdraft_in_cents)
    {
        $this->container['overdraft_in_cents'] = $overdraft_in_cents;

        return $this;
    }

    /**
     * Gets overdraft_currency
     *
     * @return string
     */
    public function getOverdraftCurrency()
    {
        return $this->container['overdraft_currency'];
    }

    /**
     * Sets overdraft_currency
     *
     * @param string $overdraft_currency The currency of the Inventory overdraft
     *
     * @return $this
     */
    public function setOverdraftCurrency($overdraft_currency)
    {
        $this->container['overdraft_currency'] = $overdraft_currency;

        return $this;
    }

    /**
     * Gets balance_in_cents
     *
     * @return float
     */
    public function getBalanceInCents()
    {
        return $this->container['balance_in_cents'];
    }

    /**
     * Sets balance_in_cents
     *
     * @param float $balance_in_cents The initial balance to be set for the new Inventory (in cents)
     *
     * @return $this
     */
    public function setBalanceInCents($balance_in_cents)
    {
        $this->container['balance_in_cents'] = $balance_in_cents;

        return $this;
    }

    /**
     * Gets balance_currency
     *
     * @return string
     */
    public function getBalanceCurrency()
    {
        return $this->container['balance_currency'];
    }

    /**
     * Sets balance_currency
     *
     * @param string $balance_currency The currency of the Inventory balance
     *
     * @return $this
     */
    public function setBalanceCurrency($balance_currency)
    {
        $this->container['balance_currency'] = $balance_currency;

        return $this;
    }

    /**
     * Gets whitelist_name
     *
     * @return string
     */
    public function getWhitelistName()
    {
        return $this->container['whitelist_name'];
    }

    /**
     * Sets whitelist_name
     *
     * @param string $whitelist_name The name of the default Whitelist that will be assigned to the new Inventory
     *
     * @return $this
     */
    public function setWhitelistName($whitelist_name)
    {
        $this->container['whitelist_name'] = $whitelist_name;

        return $this;
    }

    /**
     * Gets type
     *
     * @return string
     */
    public function getType()
    {
        return $this->container['type'];
    }

    /**
     * Sets type
     *
     * @param string $type The inventory type this inventory will have. Cannot be changed. Defaults to WHOLESALE
     *
     * @return $this
     */
    public function setType($type)
    {
        $allowedValues = $this->getTypeAllowableValues();
        if (!is_null($type) && !in_array($type, $allowedValues, true)) {
            throw new \InvalidArgumentException(
                sprintf(
                    "Invalid value for 'type', must be one of '%s'",
                    implode("', '", $allowedValues)
                )
            );
        }
        $this->container['type'] = $type;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    public function offsetExists($offset)
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed
     */
    public function offsetGet($offset)
    {
        return isset($this->container[$offset]) ? $this->container[$offset] : null;
    }

    /**
     * Sets value based on offset.
     *
     * @param integer $offset Offset
     * @param mixed   $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value)
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    public function offsetUnset($offset)
    {
        unset($this->container[$offset]);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        if (defined('JSON_PRETTY_PRINT')) { // use JSON pretty print
            return json_encode(
                ObjectSerializer::sanitizeForSerialization($this),
                JSON_PRETTY_PRINT
            );
        }

        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}
