<?php
/**
 * ResponseLocationUpdate
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Distributor PPU Service
 *
 * © KnowRoaming LTD 2017
 *
 * OpenAPI spec version: v1.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.35
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace Swagger\Client\Model;

use \ArrayAccess;
use \Swagger\Client\ObjectSerializer;

/**
 * ResponseLocationUpdate Class Doc Comment
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class ResponseLocationUpdate implements ModelInterface, ArrayAccess
{
    const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $swaggerModelName = 'ResponseLocationUpdate';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $swaggerTypes = [
        'lu_id' => 'int',
'distributor_id' => 'int',
'sim_iccid' => 'string',
'custom_imsi' => 'int',
'custom_msisdn' => 'int',
'sponsored_id' => 'int',
'sponsored_imsi' => 'int',
'sponsored_msisdn' => 'int',
'sponsored_name' => 'string',
'hlr_ssn' => 'int',
'hlr_msc_number' => 'int',
'hlr_vlr_number' => 'int',
'hlr_sgsn_number' => 'int',
'vlr_ssn' => 'int',
'vlr_msc_number' => 'int',
'vlr_vlr_number' => 'int',
'vlr_sgsn_number' => 'int',
'network_id' => 'int',
'network_name' => 'string',
'mcc' => 'string',
'mnc' => 'string',
'country_iso3' => 'string',
'country_name' => 'string',
'service_type' => 'string',
'pilot_mode_name' => 'string',
'connection_status' => 'string',
'packet_switched' => 'bool',
'mme' => 'bool',
'gt_prefix' => 'int',
'rat' => 'string',
'created_epoch_milli' => 'int',
'event_epoch_milli' => 'int',
'reject_reason' => 'string',
'imeisv' => 'string'    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $swaggerFormats = [
        'lu_id' => 'int64',
'distributor_id' => 'int32',
'sim_iccid' => null,
'custom_imsi' => 'int64',
'custom_msisdn' => 'int64',
'sponsored_id' => 'int32',
'sponsored_imsi' => 'int64',
'sponsored_msisdn' => 'int64',
'sponsored_name' => null,
'hlr_ssn' => 'int64',
'hlr_msc_number' => 'int64',
'hlr_vlr_number' => 'int64',
'hlr_sgsn_number' => 'int64',
'vlr_ssn' => 'int64',
'vlr_msc_number' => 'int64',
'vlr_vlr_number' => 'int64',
'vlr_sgsn_number' => 'int64',
'network_id' => 'int32',
'network_name' => null,
'mcc' => null,
'mnc' => null,
'country_iso3' => null,
'country_name' => null,
'service_type' => null,
'pilot_mode_name' => null,
'connection_status' => null,
'packet_switched' => null,
'mme' => null,
'gt_prefix' => 'int64',
'rat' => null,
'created_epoch_milli' => 'int64',
'event_epoch_milli' => 'int64',
'reject_reason' => null,
'imeisv' => null    ];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function swaggerTypes()
    {
        return self::$swaggerTypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function swaggerFormats()
    {
        return self::$swaggerFormats;
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'lu_id' => 'luId',
'distributor_id' => 'distributorId',
'sim_iccid' => 'simIccid',
'custom_imsi' => 'customImsi',
'custom_msisdn' => 'customMsisdn',
'sponsored_id' => 'sponsoredId',
'sponsored_imsi' => 'sponsoredImsi',
'sponsored_msisdn' => 'sponsoredMsisdn',
'sponsored_name' => 'sponsoredName',
'hlr_ssn' => 'hlrSsn',
'hlr_msc_number' => 'hlrMscNumber',
'hlr_vlr_number' => 'hlrVlrNumber',
'hlr_sgsn_number' => 'hlrSgsnNumber',
'vlr_ssn' => 'vlrSsn',
'vlr_msc_number' => 'vlrMscNumber',
'vlr_vlr_number' => 'vlrVlrNumber',
'vlr_sgsn_number' => 'vlrSgsnNumber',
'network_id' => 'networkId',
'network_name' => 'networkName',
'mcc' => 'mcc',
'mnc' => 'mnc',
'country_iso3' => 'countryIso3',
'country_name' => 'countryName',
'service_type' => 'serviceType',
'pilot_mode_name' => 'pilotModeName',
'connection_status' => 'connectionStatus',
'packet_switched' => 'packetSwitched',
'mme' => 'mme',
'gt_prefix' => 'gtPrefix',
'rat' => 'rat',
'created_epoch_milli' => 'createdEpochMilli',
'event_epoch_milli' => 'eventEpochMilli',
'reject_reason' => 'rejectReason',
'imeisv' => 'imeisv'    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'lu_id' => 'setLuId',
'distributor_id' => 'setDistributorId',
'sim_iccid' => 'setSimIccid',
'custom_imsi' => 'setCustomImsi',
'custom_msisdn' => 'setCustomMsisdn',
'sponsored_id' => 'setSponsoredId',
'sponsored_imsi' => 'setSponsoredImsi',
'sponsored_msisdn' => 'setSponsoredMsisdn',
'sponsored_name' => 'setSponsoredName',
'hlr_ssn' => 'setHlrSsn',
'hlr_msc_number' => 'setHlrMscNumber',
'hlr_vlr_number' => 'setHlrVlrNumber',
'hlr_sgsn_number' => 'setHlrSgsnNumber',
'vlr_ssn' => 'setVlrSsn',
'vlr_msc_number' => 'setVlrMscNumber',
'vlr_vlr_number' => 'setVlrVlrNumber',
'vlr_sgsn_number' => 'setVlrSgsnNumber',
'network_id' => 'setNetworkId',
'network_name' => 'setNetworkName',
'mcc' => 'setMcc',
'mnc' => 'setMnc',
'country_iso3' => 'setCountryIso3',
'country_name' => 'setCountryName',
'service_type' => 'setServiceType',
'pilot_mode_name' => 'setPilotModeName',
'connection_status' => 'setConnectionStatus',
'packet_switched' => 'setPacketSwitched',
'mme' => 'setMme',
'gt_prefix' => 'setGtPrefix',
'rat' => 'setRat',
'created_epoch_milli' => 'setCreatedEpochMilli',
'event_epoch_milli' => 'setEventEpochMilli',
'reject_reason' => 'setRejectReason',
'imeisv' => 'setImeisv'    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'lu_id' => 'getLuId',
'distributor_id' => 'getDistributorId',
'sim_iccid' => 'getSimIccid',
'custom_imsi' => 'getCustomImsi',
'custom_msisdn' => 'getCustomMsisdn',
'sponsored_id' => 'getSponsoredId',
'sponsored_imsi' => 'getSponsoredImsi',
'sponsored_msisdn' => 'getSponsoredMsisdn',
'sponsored_name' => 'getSponsoredName',
'hlr_ssn' => 'getHlrSsn',
'hlr_msc_number' => 'getHlrMscNumber',
'hlr_vlr_number' => 'getHlrVlrNumber',
'hlr_sgsn_number' => 'getHlrSgsnNumber',
'vlr_ssn' => 'getVlrSsn',
'vlr_msc_number' => 'getVlrMscNumber',
'vlr_vlr_number' => 'getVlrVlrNumber',
'vlr_sgsn_number' => 'getVlrSgsnNumber',
'network_id' => 'getNetworkId',
'network_name' => 'getNetworkName',
'mcc' => 'getMcc',
'mnc' => 'getMnc',
'country_iso3' => 'getCountryIso3',
'country_name' => 'getCountryName',
'service_type' => 'getServiceType',
'pilot_mode_name' => 'getPilotModeName',
'connection_status' => 'getConnectionStatus',
'packet_switched' => 'getPacketSwitched',
'mme' => 'getMme',
'gt_prefix' => 'getGtPrefix',
'rat' => 'getRat',
'created_epoch_milli' => 'getCreatedEpochMilli',
'event_epoch_milli' => 'getEventEpochMilli',
'reject_reason' => 'getRejectReason',
'imeisv' => 'getImeisv'    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$swaggerModelName;
    }

    

    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[] $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->container['lu_id'] = isset($data['lu_id']) ? $data['lu_id'] : null;
        $this->container['distributor_id'] = isset($data['distributor_id']) ? $data['distributor_id'] : null;
        $this->container['sim_iccid'] = isset($data['sim_iccid']) ? $data['sim_iccid'] : null;
        $this->container['custom_imsi'] = isset($data['custom_imsi']) ? $data['custom_imsi'] : null;
        $this->container['custom_msisdn'] = isset($data['custom_msisdn']) ? $data['custom_msisdn'] : null;
        $this->container['sponsored_id'] = isset($data['sponsored_id']) ? $data['sponsored_id'] : null;
        $this->container['sponsored_imsi'] = isset($data['sponsored_imsi']) ? $data['sponsored_imsi'] : null;
        $this->container['sponsored_msisdn'] = isset($data['sponsored_msisdn']) ? $data['sponsored_msisdn'] : null;
        $this->container['sponsored_name'] = isset($data['sponsored_name']) ? $data['sponsored_name'] : null;
        $this->container['hlr_ssn'] = isset($data['hlr_ssn']) ? $data['hlr_ssn'] : null;
        $this->container['hlr_msc_number'] = isset($data['hlr_msc_number']) ? $data['hlr_msc_number'] : null;
        $this->container['hlr_vlr_number'] = isset($data['hlr_vlr_number']) ? $data['hlr_vlr_number'] : null;
        $this->container['hlr_sgsn_number'] = isset($data['hlr_sgsn_number']) ? $data['hlr_sgsn_number'] : null;
        $this->container['vlr_ssn'] = isset($data['vlr_ssn']) ? $data['vlr_ssn'] : null;
        $this->container['vlr_msc_number'] = isset($data['vlr_msc_number']) ? $data['vlr_msc_number'] : null;
        $this->container['vlr_vlr_number'] = isset($data['vlr_vlr_number']) ? $data['vlr_vlr_number'] : null;
        $this->container['vlr_sgsn_number'] = isset($data['vlr_sgsn_number']) ? $data['vlr_sgsn_number'] : null;
        $this->container['network_id'] = isset($data['network_id']) ? $data['network_id'] : null;
        $this->container['network_name'] = isset($data['network_name']) ? $data['network_name'] : null;
        $this->container['mcc'] = isset($data['mcc']) ? $data['mcc'] : null;
        $this->container['mnc'] = isset($data['mnc']) ? $data['mnc'] : null;
        $this->container['country_iso3'] = isset($data['country_iso3']) ? $data['country_iso3'] : null;
        $this->container['country_name'] = isset($data['country_name']) ? $data['country_name'] : null;
        $this->container['service_type'] = isset($data['service_type']) ? $data['service_type'] : null;
        $this->container['pilot_mode_name'] = isset($data['pilot_mode_name']) ? $data['pilot_mode_name'] : null;
        $this->container['connection_status'] = isset($data['connection_status']) ? $data['connection_status'] : null;
        $this->container['packet_switched'] = isset($data['packet_switched']) ? $data['packet_switched'] : false;
        $this->container['mme'] = isset($data['mme']) ? $data['mme'] : false;
        $this->container['gt_prefix'] = isset($data['gt_prefix']) ? $data['gt_prefix'] : null;
        $this->container['rat'] = isset($data['rat']) ? $data['rat'] : null;
        $this->container['created_epoch_milli'] = isset($data['created_epoch_milli']) ? $data['created_epoch_milli'] : null;
        $this->container['event_epoch_milli'] = isset($data['event_epoch_milli']) ? $data['event_epoch_milli'] : null;
        $this->container['reject_reason'] = isset($data['reject_reason']) ? $data['reject_reason'] : null;
        $this->container['imeisv'] = isset($data['imeisv']) ? $data['imeisv'] : null;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets lu_id
     *
     * @return int
     */
    public function getLuId()
    {
        return $this->container['lu_id'];
    }

    /**
     * Sets lu_id
     *
     * @param int $lu_id lu_id
     *
     * @return $this
     */
    public function setLuId($lu_id)
    {
        $this->container['lu_id'] = $lu_id;

        return $this;
    }

    /**
     * Gets distributor_id
     *
     * @return int
     */
    public function getDistributorId()
    {
        return $this->container['distributor_id'];
    }

    /**
     * Sets distributor_id
     *
     * @param int $distributor_id distributor_id
     *
     * @return $this
     */
    public function setDistributorId($distributor_id)
    {
        $this->container['distributor_id'] = $distributor_id;

        return $this;
    }

    /**
     * Gets sim_iccid
     *
     * @return string
     */
    public function getSimIccid()
    {
        return $this->container['sim_iccid'];
    }

    /**
     * Sets sim_iccid
     *
     * @param string $sim_iccid sim_iccid
     *
     * @return $this
     */
    public function setSimIccid($sim_iccid)
    {
        $this->container['sim_iccid'] = $sim_iccid;

        return $this;
    }

    /**
     * Gets custom_imsi
     *
     * @return int
     */
    public function getCustomImsi()
    {
        return $this->container['custom_imsi'];
    }

    /**
     * Sets custom_imsi
     *
     * @param int $custom_imsi custom_imsi
     *
     * @return $this
     */
    public function setCustomImsi($custom_imsi)
    {
        $this->container['custom_imsi'] = $custom_imsi;

        return $this;
    }

    /**
     * Gets custom_msisdn
     *
     * @return int
     */
    public function getCustomMsisdn()
    {
        return $this->container['custom_msisdn'];
    }

    /**
     * Sets custom_msisdn
     *
     * @param int $custom_msisdn custom_msisdn
     *
     * @return $this
     */
    public function setCustomMsisdn($custom_msisdn)
    {
        $this->container['custom_msisdn'] = $custom_msisdn;

        return $this;
    }

    /**
     * Gets sponsored_id
     *
     * @return int
     */
    public function getSponsoredId()
    {
        return $this->container['sponsored_id'];
    }

    /**
     * Sets sponsored_id
     *
     * @param int $sponsored_id sponsored_id
     *
     * @return $this
     */
    public function setSponsoredId($sponsored_id)
    {
        $this->container['sponsored_id'] = $sponsored_id;

        return $this;
    }

    /**
     * Gets sponsored_imsi
     *
     * @return int
     */
    public function getSponsoredImsi()
    {
        return $this->container['sponsored_imsi'];
    }

    /**
     * Sets sponsored_imsi
     *
     * @param int $sponsored_imsi sponsored_imsi
     *
     * @return $this
     */
    public function setSponsoredImsi($sponsored_imsi)
    {
        $this->container['sponsored_imsi'] = $sponsored_imsi;

        return $this;
    }

    /**
     * Gets sponsored_msisdn
     *
     * @return int
     */
    public function getSponsoredMsisdn()
    {
        return $this->container['sponsored_msisdn'];
    }

    /**
     * Sets sponsored_msisdn
     *
     * @param int $sponsored_msisdn sponsored_msisdn
     *
     * @return $this
     */
    public function setSponsoredMsisdn($sponsored_msisdn)
    {
        $this->container['sponsored_msisdn'] = $sponsored_msisdn;

        return $this;
    }

    /**
     * Gets sponsored_name
     *
     * @return string
     */
    public function getSponsoredName()
    {
        return $this->container['sponsored_name'];
    }

    /**
     * Sets sponsored_name
     *
     * @param string $sponsored_name sponsored_name
     *
     * @return $this
     */
    public function setSponsoredName($sponsored_name)
    {
        $this->container['sponsored_name'] = $sponsored_name;

        return $this;
    }

    /**
     * Gets hlr_ssn
     *
     * @return int
     */
    public function getHlrSsn()
    {
        return $this->container['hlr_ssn'];
    }

    /**
     * Sets hlr_ssn
     *
     * @param int $hlr_ssn hlr_ssn
     *
     * @return $this
     */
    public function setHlrSsn($hlr_ssn)
    {
        $this->container['hlr_ssn'] = $hlr_ssn;

        return $this;
    }

    /**
     * Gets hlr_msc_number
     *
     * @return int
     */
    public function getHlrMscNumber()
    {
        return $this->container['hlr_msc_number'];
    }

    /**
     * Sets hlr_msc_number
     *
     * @param int $hlr_msc_number hlr_msc_number
     *
     * @return $this
     */
    public function setHlrMscNumber($hlr_msc_number)
    {
        $this->container['hlr_msc_number'] = $hlr_msc_number;

        return $this;
    }

    /**
     * Gets hlr_vlr_number
     *
     * @return int
     */
    public function getHlrVlrNumber()
    {
        return $this->container['hlr_vlr_number'];
    }

    /**
     * Sets hlr_vlr_number
     *
     * @param int $hlr_vlr_number hlr_vlr_number
     *
     * @return $this
     */
    public function setHlrVlrNumber($hlr_vlr_number)
    {
        $this->container['hlr_vlr_number'] = $hlr_vlr_number;

        return $this;
    }

    /**
     * Gets hlr_sgsn_number
     *
     * @return int
     */
    public function getHlrSgsnNumber()
    {
        return $this->container['hlr_sgsn_number'];
    }

    /**
     * Sets hlr_sgsn_number
     *
     * @param int $hlr_sgsn_number hlr_sgsn_number
     *
     * @return $this
     */
    public function setHlrSgsnNumber($hlr_sgsn_number)
    {
        $this->container['hlr_sgsn_number'] = $hlr_sgsn_number;

        return $this;
    }

    /**
     * Gets vlr_ssn
     *
     * @return int
     */
    public function getVlrSsn()
    {
        return $this->container['vlr_ssn'];
    }

    /**
     * Sets vlr_ssn
     *
     * @param int $vlr_ssn vlr_ssn
     *
     * @return $this
     */
    public function setVlrSsn($vlr_ssn)
    {
        $this->container['vlr_ssn'] = $vlr_ssn;

        return $this;
    }

    /**
     * Gets vlr_msc_number
     *
     * @return int
     */
    public function getVlrMscNumber()
    {
        return $this->container['vlr_msc_number'];
    }

    /**
     * Sets vlr_msc_number
     *
     * @param int $vlr_msc_number vlr_msc_number
     *
     * @return $this
     */
    public function setVlrMscNumber($vlr_msc_number)
    {
        $this->container['vlr_msc_number'] = $vlr_msc_number;

        return $this;
    }

    /**
     * Gets vlr_vlr_number
     *
     * @return int
     */
    public function getVlrVlrNumber()
    {
        return $this->container['vlr_vlr_number'];
    }

    /**
     * Sets vlr_vlr_number
     *
     * @param int $vlr_vlr_number vlr_vlr_number
     *
     * @return $this
     */
    public function setVlrVlrNumber($vlr_vlr_number)
    {
        $this->container['vlr_vlr_number'] = $vlr_vlr_number;

        return $this;
    }

    /**
     * Gets vlr_sgsn_number
     *
     * @return int
     */
    public function getVlrSgsnNumber()
    {
        return $this->container['vlr_sgsn_number'];
    }

    /**
     * Sets vlr_sgsn_number
     *
     * @param int $vlr_sgsn_number vlr_sgsn_number
     *
     * @return $this
     */
    public function setVlrSgsnNumber($vlr_sgsn_number)
    {
        $this->container['vlr_sgsn_number'] = $vlr_sgsn_number;

        return $this;
    }

    /**
     * Gets network_id
     *
     * @return int
     */
    public function getNetworkId()
    {
        return $this->container['network_id'];
    }

    /**
     * Sets network_id
     *
     * @param int $network_id network_id
     *
     * @return $this
     */
    public function setNetworkId($network_id)
    {
        $this->container['network_id'] = $network_id;

        return $this;
    }

    /**
     * Gets network_name
     *
     * @return string
     */
    public function getNetworkName()
    {
        return $this->container['network_name'];
    }

    /**
     * Sets network_name
     *
     * @param string $network_name network_name
     *
     * @return $this
     */
    public function setNetworkName($network_name)
    {
        $this->container['network_name'] = $network_name;

        return $this;
    }

    /**
     * Gets mcc
     *
     * @return string
     */
    public function getMcc()
    {
        return $this->container['mcc'];
    }

    /**
     * Sets mcc
     *
     * @param string $mcc mcc
     *
     * @return $this
     */
    public function setMcc($mcc)
    {
        $this->container['mcc'] = $mcc;

        return $this;
    }

    /**
     * Gets mnc
     *
     * @return string
     */
    public function getMnc()
    {
        return $this->container['mnc'];
    }

    /**
     * Sets mnc
     *
     * @param string $mnc mnc
     *
     * @return $this
     */
    public function setMnc($mnc)
    {
        $this->container['mnc'] = $mnc;

        return $this;
    }

    /**
     * Gets country_iso3
     *
     * @return string
     */
    public function getCountryIso3()
    {
        return $this->container['country_iso3'];
    }

    /**
     * Sets country_iso3
     *
     * @param string $country_iso3 country_iso3
     *
     * @return $this
     */
    public function setCountryIso3($country_iso3)
    {
        $this->container['country_iso3'] = $country_iso3;

        return $this;
    }

    /**
     * Gets country_name
     *
     * @return string
     */
    public function getCountryName()
    {
        return $this->container['country_name'];
    }

    /**
     * Sets country_name
     *
     * @param string $country_name country_name
     *
     * @return $this
     */
    public function setCountryName($country_name)
    {
        $this->container['country_name'] = $country_name;

        return $this;
    }

    /**
     * Gets service_type
     *
     * @return string
     */
    public function getServiceType()
    {
        return $this->container['service_type'];
    }

    /**
     * Sets service_type
     *
     * @param string $service_type service_type
     *
     * @return $this
     */
    public function setServiceType($service_type)
    {
        $this->container['service_type'] = $service_type;

        return $this;
    }

    /**
     * Gets pilot_mode_name
     *
     * @return string
     */
    public function getPilotModeName()
    {
        return $this->container['pilot_mode_name'];
    }

    /**
     * Sets pilot_mode_name
     *
     * @param string $pilot_mode_name pilot_mode_name
     *
     * @return $this
     */
    public function setPilotModeName($pilot_mode_name)
    {
        $this->container['pilot_mode_name'] = $pilot_mode_name;

        return $this;
    }

    /**
     * Gets connection_status
     *
     * @return string
     */
    public function getConnectionStatus()
    {
        return $this->container['connection_status'];
    }

    /**
     * Sets connection_status
     *
     * @param string $connection_status connection_status
     *
     * @return $this
     */
    public function setConnectionStatus($connection_status)
    {
        $this->container['connection_status'] = $connection_status;

        return $this;
    }

    /**
     * Gets packet_switched
     *
     * @return bool
     */
    public function getPacketSwitched()
    {
        return $this->container['packet_switched'];
    }

    /**
     * Sets packet_switched
     *
     * @param bool $packet_switched packet_switched
     *
     * @return $this
     */
    public function setPacketSwitched($packet_switched)
    {
        $this->container['packet_switched'] = $packet_switched;

        return $this;
    }

    /**
     * Gets mme
     *
     * @return bool
     */
    public function getMme()
    {
        return $this->container['mme'];
    }

    /**
     * Sets mme
     *
     * @param bool $mme mme
     *
     * @return $this
     */
    public function setMme($mme)
    {
        $this->container['mme'] = $mme;

        return $this;
    }

    /**
     * Gets gt_prefix
     *
     * @return int
     */
    public function getGtPrefix()
    {
        return $this->container['gt_prefix'];
    }

    /**
     * Sets gt_prefix
     *
     * @param int $gt_prefix gt_prefix
     *
     * @return $this
     */
    public function setGtPrefix($gt_prefix)
    {
        $this->container['gt_prefix'] = $gt_prefix;

        return $this;
    }

    /**
     * Gets rat
     *
     * @return string
     */
    public function getRat()
    {
        return $this->container['rat'];
    }

    /**
     * Sets rat
     *
     * @param string $rat rat
     *
     * @return $this
     */
    public function setRat($rat)
    {
        $this->container['rat'] = $rat;

        return $this;
    }

    /**
     * Gets created_epoch_milli
     *
     * @return int
     */
    public function getCreatedEpochMilli()
    {
        return $this->container['created_epoch_milli'];
    }

    /**
     * Sets created_epoch_milli
     *
     * @param int $created_epoch_milli created_epoch_milli
     *
     * @return $this
     */
    public function setCreatedEpochMilli($created_epoch_milli)
    {
        $this->container['created_epoch_milli'] = $created_epoch_milli;

        return $this;
    }

    /**
     * Gets event_epoch_milli
     *
     * @return int
     */
    public function getEventEpochMilli()
    {
        return $this->container['event_epoch_milli'];
    }

    /**
     * Sets event_epoch_milli
     *
     * @param int $event_epoch_milli event_epoch_milli
     *
     * @return $this
     */
    public function setEventEpochMilli($event_epoch_milli)
    {
        $this->container['event_epoch_milli'] = $event_epoch_milli;

        return $this;
    }

    /**
     * Gets reject_reason
     *
     * @return string
     */
    public function getRejectReason()
    {
        return $this->container['reject_reason'];
    }

    /**
     * Sets reject_reason
     *
     * @param string $reject_reason reject_reason
     *
     * @return $this
     */
    public function setRejectReason($reject_reason)
    {
        $this->container['reject_reason'] = $reject_reason;

        return $this;
    }

    /**
     * Gets imeisv
     *
     * @return string
     */
    public function getImeisv()
    {
        return $this->container['imeisv'];
    }

    /**
     * Sets imeisv
     *
     * @param string $imeisv imeisv
     *
     * @return $this
     */
    public function setImeisv($imeisv)
    {
        $this->container['imeisv'] = $imeisv;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    public function offsetExists($offset)
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed
     */
    public function offsetGet($offset)
    {
        return isset($this->container[$offset]) ? $this->container[$offset] : null;
    }

    /**
     * Sets value based on offset.
     *
     * @param integer $offset Offset
     * @param mixed   $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value)
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    public function offsetUnset($offset)
    {
        unset($this->container[$offset]);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        if (defined('JSON_PRETTY_PRINT')) { // use JSON pretty print
            return json_encode(
                ObjectSerializer::sanitizeForSerialization($this),
                JSON_PRETTY_PRINT
            );
        }

        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}
