<?php
/**
 * ResponseImsiSlotProfile
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Distributor PPU Service
 *
 * © KnowRoaming LTD 2017
 *
 * OpenAPI spec version: v1.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.35
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace Swagger\Client\Model;

use \ArrayAccess;
use \Swagger\Client\ObjectSerializer;

/**
 * ResponseImsiSlotProfile Class Doc Comment
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class ResponseImsiSlotProfile implements ModelInterface, ArrayAccess
{
    const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $swaggerModelName = 'ResponseImsiSlotProfile';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $swaggerTypes = [
        'id' => 'int',
'imsi_slot_profile_id' => 'string',
'imsi_slot_profile_name' => 'string',
'imsi_slot_mapping' => '\Swagger\Client\Model\ResponseImsiSlotMapping[]',
'date_created_epoch' => 'int',
'date_modified_epoch' => 'int'    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $swaggerFormats = [
        'id' => 'int32',
'imsi_slot_profile_id' => null,
'imsi_slot_profile_name' => null,
'imsi_slot_mapping' => null,
'date_created_epoch' => 'int64',
'date_modified_epoch' => 'int64'    ];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function swaggerTypes()
    {
        return self::$swaggerTypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function swaggerFormats()
    {
        return self::$swaggerFormats;
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'id' => 'id',
'imsi_slot_profile_id' => 'imsiSlotProfileId',
'imsi_slot_profile_name' => 'imsiSlotProfileName',
'imsi_slot_mapping' => 'imsiSlotMapping',
'date_created_epoch' => 'dateCreatedEpoch',
'date_modified_epoch' => 'dateModifiedEpoch'    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'id' => 'setId',
'imsi_slot_profile_id' => 'setImsiSlotProfileId',
'imsi_slot_profile_name' => 'setImsiSlotProfileName',
'imsi_slot_mapping' => 'setImsiSlotMapping',
'date_created_epoch' => 'setDateCreatedEpoch',
'date_modified_epoch' => 'setDateModifiedEpoch'    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'id' => 'getId',
'imsi_slot_profile_id' => 'getImsiSlotProfileId',
'imsi_slot_profile_name' => 'getImsiSlotProfileName',
'imsi_slot_mapping' => 'getImsiSlotMapping',
'date_created_epoch' => 'getDateCreatedEpoch',
'date_modified_epoch' => 'getDateModifiedEpoch'    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$swaggerModelName;
    }

    

    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[] $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->container['id'] = isset($data['id']) ? $data['id'] : null;
        $this->container['imsi_slot_profile_id'] = isset($data['imsi_slot_profile_id']) ? $data['imsi_slot_profile_id'] : null;
        $this->container['imsi_slot_profile_name'] = isset($data['imsi_slot_profile_name']) ? $data['imsi_slot_profile_name'] : null;
        $this->container['imsi_slot_mapping'] = isset($data['imsi_slot_mapping']) ? $data['imsi_slot_mapping'] : null;
        $this->container['date_created_epoch'] = isset($data['date_created_epoch']) ? $data['date_created_epoch'] : null;
        $this->container['date_modified_epoch'] = isset($data['date_modified_epoch']) ? $data['date_modified_epoch'] : null;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        if ($this->container['imsi_slot_profile_id'] === null) {
            $invalidProperties[] = "'imsi_slot_profile_id' can't be null";
        }
        if ($this->container['imsi_slot_profile_name'] === null) {
            $invalidProperties[] = "'imsi_slot_profile_name' can't be null";
        }
        if ($this->container['imsi_slot_mapping'] === null) {
            $invalidProperties[] = "'imsi_slot_mapping' can't be null";
        }
        if ($this->container['date_created_epoch'] === null) {
            $invalidProperties[] = "'date_created_epoch' can't be null";
        }
        if ($this->container['date_modified_epoch'] === null) {
            $invalidProperties[] = "'date_modified_epoch' can't be null";
        }
        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets id
     *
     * @return int
     */
    public function getId()
    {
        return $this->container['id'];
    }

    /**
     * Sets id
     *
     * @param int $id The IMSI Slot Profile id
     *
     * @return $this
     */
    public function setId($id)
    {
        $this->container['id'] = $id;

        return $this;
    }

    /**
     * Gets imsi_slot_profile_id
     *
     * @return string
     */
    public function getImsiSlotProfileId()
    {
        return $this->container['imsi_slot_profile_id'];
    }

    /**
     * Sets imsi_slot_profile_id
     *
     * @param string $imsi_slot_profile_id The unique identifier of IMSI Slot Profile
     *
     * @return $this
     */
    public function setImsiSlotProfileId($imsi_slot_profile_id)
    {
        $this->container['imsi_slot_profile_id'] = $imsi_slot_profile_id;

        return $this;
    }

    /**
     * Gets imsi_slot_profile_name
     *
     * @return string
     */
    public function getImsiSlotProfileName()
    {
        return $this->container['imsi_slot_profile_name'];
    }

    /**
     * Sets imsi_slot_profile_name
     *
     * @param string $imsi_slot_profile_name The IMSI Slot Profile name
     *
     * @return $this
     */
    public function setImsiSlotProfileName($imsi_slot_profile_name)
    {
        $this->container['imsi_slot_profile_name'] = $imsi_slot_profile_name;

        return $this;
    }

    /**
     * Gets imsi_slot_mapping
     *
     * @return \Swagger\Client\Model\ResponseImsiSlotMapping[]
     */
    public function getImsiSlotMapping()
    {
        return $this->container['imsi_slot_mapping'];
    }

    /**
     * Sets imsi_slot_mapping
     *
     * @param \Swagger\Client\Model\ResponseImsiSlotMapping[] $imsi_slot_mapping The IMSI Slot Mapping
     *
     * @return $this
     */
    public function setImsiSlotMapping($imsi_slot_mapping)
    {
        $this->container['imsi_slot_mapping'] = $imsi_slot_mapping;

        return $this;
    }

    /**
     * Gets date_created_epoch
     *
     * @return int
     */
    public function getDateCreatedEpoch()
    {
        return $this->container['date_created_epoch'];
    }

    /**
     * Sets date_created_epoch
     *
     * @param int $date_created_epoch The IMSI Slot Profile created epoch time
     *
     * @return $this
     */
    public function setDateCreatedEpoch($date_created_epoch)
    {
        $this->container['date_created_epoch'] = $date_created_epoch;

        return $this;
    }

    /**
     * Gets date_modified_epoch
     *
     * @return int
     */
    public function getDateModifiedEpoch()
    {
        return $this->container['date_modified_epoch'];
    }

    /**
     * Sets date_modified_epoch
     *
     * @param int $date_modified_epoch The IMSI Slot Profile modified epoch time
     *
     * @return $this
     */
    public function setDateModifiedEpoch($date_modified_epoch)
    {
        $this->container['date_modified_epoch'] = $date_modified_epoch;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    public function offsetExists($offset)
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed
     */
    public function offsetGet($offset)
    {
        return isset($this->container[$offset]) ? $this->container[$offset] : null;
    }

    /**
     * Sets value based on offset.
     *
     * @param integer $offset Offset
     * @param mixed   $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value)
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    public function offsetUnset($offset)
    {
        unset($this->container[$offset]);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        if (defined('JSON_PRETTY_PRINT')) { // use JSON pretty print
            return json_encode(
                ObjectSerializer::sanitizeForSerialization($this),
                JSON_PRETTY_PRINT
            );
        }

        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}
