<?php
/**
 * RequestWhitelistEntryTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Distributor PPU Service
 *
 * © KnowRoaming LTD 2017
 *
 * OpenAPI spec version: v1.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.35
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

/**
 * RequestWhitelistEntryTest Class Doc Comment
 *
 * @category    Class
 * @description RequestWhitelistEntry
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class RequestWhitelistEntryTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "RequestWhitelistEntry"
     */
    public function testRequestWhitelistEntry()
    {
    }

    /**
     * Test attribute "country_iso3"
     */
    public function testPropertyCountryIso3()
    {
    }

    /**
     * Test attribute "sponsor_imsi_id"
     */
    public function testPropertySponsorImsiId()
    {
    }

    /**
     * Test attribute "network_id"
     */
    public function testPropertyNetworkId()
    {
    }

    /**
     * Test attribute "new_voice_status"
     */
    public function testPropertyNewVoiceStatus()
    {
    }

    /**
     * Test attribute "new_sms_status"
     */
    public function testPropertyNewSmsStatus()
    {
    }

    /**
     * Test attribute "new_data_status"
     */
    public function testPropertyNewDataStatus()
    {
    }
}
