<?php
/**
 * RequestSendSmsBinaryCustomTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Distributor PPU Service
 *
 * © KnowRoaming LTD 2017
 *
 * OpenAPI spec version: v1.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.35
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

/**
 * RequestSendSmsBinaryCustomTest Class Doc Comment
 *
 * @category    Class
 * @description RequestSendSmsBinaryCustom
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class RequestSendSmsBinaryCustomTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "RequestSendSmsBinaryCustom"
     */
    public function testRequestSendSmsBinaryCustom()
    {
    }

    /**
     * Test attribute "sender_cli"
     */
    public function testPropertySenderCli()
    {
    }

    /**
     * Test attribute "hex_message"
     */
    public function testPropertyHexMessage()
    {
    }

    /**
     * Test attribute "esm_class"
     */
    public function testPropertyEsmClass()
    {
    }

    /**
     * Test attribute "pid"
     */
    public function testPropertyPid()
    {
    }

    /**
     * Test attribute "dcs"
     */
    public function testPropertyDcs()
    {
    }

    /**
     * Test attribute "validity_period_seconds"
     */
    public function testPropertyValidityPeriodSeconds()
    {
    }

    /**
     * Test attribute "udh_hex_string"
     */
    public function testPropertyUdhHexString()
    {
    }
}
