<?php
/**
 * ResponseSearchPackageTypeTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Distributor PPU Service
 *
 * © KnowRoaming LTD 2017
 *
 * OpenAPI spec version: v1.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.35
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

/**
 * ResponseSearchPackageTypeTest Class Doc Comment
 *
 * @category    Class
 * @description ResponseSearchPackageType
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class ResponseSearchPackageTypeTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "ResponseSearchPackageType"
     */
    public function testResponseSearchPackageType()
    {
    }

    /**
     * Test attribute "package_type_id"
     */
    public function testPropertyPackageTypeId()
    {
    }

    /**
     * Test attribute "name"
     */
    public function testPropertyName()
    {
    }

    /**
     * Test attribute "supported_countries"
     */
    public function testPropertySupportedCountries()
    {
    }

    /**
     * Test attribute "preferred_imsi_id"
     */
    public function testPropertyPreferredImsiId()
    {
    }

    /**
     * Test attribute "voice_usage_allowance_in_seconds"
     */
    public function testPropertyVoiceUsageAllowanceInSeconds()
    {
    }

    /**
     * Test attribute "data_usage_allowance_in_bytes"
     */
    public function testPropertyDataUsageAllowanceInBytes()
    {
    }

    /**
     * Test attribute "sms_usage_allowance_in_nums"
     */
    public function testPropertySmsUsageAllowanceInNums()
    {
    }

    /**
     * Test attribute "time_allowance_in_seconds"
     */
    public function testPropertyTimeAllowanceInSeconds()
    {
    }

    /**
     * Test attribute "epoch_earliest_activation"
     */
    public function testPropertyEpochEarliestActivation()
    {
    }

    /**
     * Test attribute "activation_time_allowance_in_seconds"
     */
    public function testPropertyActivationTimeAllowanceInSeconds()
    {
    }

    /**
     * Test attribute "activation_type"
     */
    public function testPropertyActivationType()
    {
    }

    /**
     * Test attribute "epoch_earliest_available"
     */
    public function testPropertyEpochEarliestAvailable()
    {
    }

    /**
     * Test attribute "epoch_latest_available"
     */
    public function testPropertyEpochLatestAvailable()
    {
    }

    /**
     * Test attribute "notes"
     */
    public function testPropertyNotes()
    {
    }

    /**
     * Test attribute "data_usage_allowance_type"
     */
    public function testPropertyDataUsageAllowanceType()
    {
    }

    /**
     * Test attribute "voice_usage_allowance_type"
     */
    public function testPropertyVoiceUsageAllowanceType()
    {
    }

    /**
     * Test attribute "sms_usage_allowance_type"
     */
    public function testPropertySmsUsageAllowanceType()
    {
    }

    /**
     * Test attribute "epoch_created"
     */
    public function testPropertyEpochCreated()
    {
    }

    /**
     * Test attribute "epoch_modified"
     */
    public function testPropertyEpochModified()
    {
    }

    /**
     * Test attribute "traffic_policy_id"
     */
    public function testPropertyTrafficPolicyId()
    {
    }

    /**
     * Test attribute "network_plan_id"
     */
    public function testPropertyNetworkPlanId()
    {
    }

    /**
     * Test attribute "description"
     */
    public function testPropertyDescription()
    {
    }

    /**
     * Test attribute "distributor_ids"
     */
    public function testPropertyDistributorIds()
    {
    }

    /**
     * Test attribute "inventory_ids"
     */
    public function testPropertyInventoryIds()
    {
    }

    /**
     * Test attribute "epoch_max_modified"
     */
    public function testPropertyEpochMaxModified()
    {
    }

    /**
     * Test attribute "time_allowance_duration"
     */
    public function testPropertyTimeAllowanceDuration()
    {
    }

    /**
     * Test attribute "time_allowance_unit"
     */
    public function testPropertyTimeAllowanceUnit()
    {
    }

    /**
     * Test attribute "status"
     */
    public function testPropertyStatus()
    {
    }
}
