<?php
/**
 * ResponseNetworkAccessEntryTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Distributor PPU Service
 *
 * © KnowRoaming LTD 2017
 *
 * OpenAPI spec version: v1.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.35
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

/**
 * ResponseNetworkAccessEntryTest Class Doc Comment
 *
 * @category    Class
 * @description ResponseNetworkAccessEntry
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class ResponseNetworkAccessEntryTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "ResponseNetworkAccessEntry"
     */
    public function testResponseNetworkAccessEntry()
    {
    }

    /**
     * Test attribute "country_iso3"
     */
    public function testPropertyCountryIso3()
    {
    }

    /**
     * Test attribute "country_name"
     */
    public function testPropertyCountryName()
    {
    }

    /**
     * Test attribute "imsi_id"
     */
    public function testPropertyImsiId()
    {
    }

    /**
     * Test attribute "network_id"
     */
    public function testPropertyNetworkId()
    {
    }

    /**
     * Test attribute "network_name"
     */
    public function testPropertyNetworkName()
    {
    }

    /**
     * Test attribute "data_status"
     */
    public function testPropertyDataStatus()
    {
    }

    /**
     * Test attribute "data_status_options"
     */
    public function testPropertyDataStatusOptions()
    {
    }

    /**
     * Test attribute "voice_status"
     */
    public function testPropertyVoiceStatus()
    {
    }

    /**
     * Test attribute "voice_status_options"
     */
    public function testPropertyVoiceStatusOptions()
    {
    }

    /**
     * Test attribute "sms_status"
     */
    public function testPropertySmsStatus()
    {
    }

    /**
     * Test attribute "sms_status_options"
     */
    public function testPropertySmsStatusOptions()
    {
    }

    /**
     * Test attribute "is_lte_enabled"
     */
    public function testPropertyIsLteEnabled()
    {
    }
}
