<?php
/**
 * ResponseVoiceCdrTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Distributor PPU Service
 *
 * © KnowRoaming LTD 2017
 *
 * OpenAPI spec version: v1.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.35
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

/**
 * ResponseVoiceCdrTest Class Doc Comment
 *
 * @category    Class
 * @description ResponseVoiceCdr
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class ResponseVoiceCdrTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "ResponseVoiceCdr"
     */
    public function testResponseVoiceCdr()
    {
    }

    /**
     * Test attribute "event_id"
     */
    public function testPropertyEventId()
    {
    }

    /**
     * Test attribute "event_name"
     */
    public function testPropertyEventName()
    {
    }

    /**
     * Test attribute "event_epoch_milli"
     */
    public function testPropertyEventEpochMilli()
    {
    }

    /**
     * Test attribute "cdr_id"
     */
    public function testPropertyCdrId()
    {
    }

    /**
     * Test attribute "distributor_id"
     */
    public function testPropertyDistributorId()
    {
    }

    /**
     * Test attribute "sim_iccid"
     */
    public function testPropertySimIccid()
    {
    }

    /**
     * Test attribute "custom_imsi"
     */
    public function testPropertyCustomImsi()
    {
    }

    /**
     * Test attribute "sponsored_id"
     */
    public function testPropertySponsoredId()
    {
    }

    /**
     * Test attribute "sponsored_imsi"
     */
    public function testPropertySponsoredImsi()
    {
    }

    /**
     * Test attribute "duration_second"
     */
    public function testPropertyDurationSecond()
    {
    }

    /**
     * Test attribute "duration_second_rounded"
     */
    public function testPropertyDurationSecondRounded()
    {
    }

    /**
     * Test attribute "network_id"
     */
    public function testPropertyNetworkId()
    {
    }

    /**
     * Test attribute "network_name"
     */
    public function testPropertyNetworkName()
    {
    }

    /**
     * Test attribute "mcc"
     */
    public function testPropertyMcc()
    {
    }

    /**
     * Test attribute "mnc"
     */
    public function testPropertyMnc()
    {
    }

    /**
     * Test attribute "country_iso3"
     */
    public function testPropertyCountryIso3()
    {
    }

    /**
     * Test attribute "country_name"
     */
    public function testPropertyCountryName()
    {
    }

    /**
     * Test attribute "package_id"
     */
    public function testPropertyPackageId()
    {
    }

    /**
     * Test attribute "package_template_name"
     */
    public function testPropertyPackageTemplateName()
    {
    }

    /**
     * Test attribute "package_template_id"
     */
    public function testPropertyPackageTemplateId()
    {
    }

    /**
     * Test attribute "service_type"
     */
    public function testPropertyServiceType()
    {
    }

    /**
     * Test attribute "calling_party_number"
     */
    public function testPropertyCallingPartyNumber()
    {
    }

    /**
     * Test attribute "called_party_number"
     */
    public function testPropertyCalledPartyNumber()
    {
    }

    /**
     * Test attribute "gt_prefix"
     */
    public function testPropertyGtPrefix()
    {
    }

    /**
     * Test attribute "open_epoch_milli"
     */
    public function testPropertyOpenEpochMilli()
    {
    }

    /**
     * Test attribute "costs"
     */
    public function testPropertyCosts()
    {
    }
}
