<?php
/**
 * ResponseSearchWhitelistTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Distributor PPU Service
 *
 * © KnowRoaming LTD 2017
 *
 * OpenAPI spec version: v1.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.35
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

/**
 * ResponseSearchWhitelistTest Class Doc Comment
 *
 * @category    Class
 * @description ResponseSearchWhitelist
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class ResponseSearchWhitelistTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "ResponseSearchWhitelist"
     */
    public function testResponseSearchWhitelist()
    {
    }

    /**
     * Test attribute "whitelist_id"
     */
    public function testPropertyWhitelistId()
    {
    }

    /**
     * Test attribute "ocs_whitelist_id"
     */
    public function testPropertyOcsWhitelistId()
    {
    }

    /**
     * Test attribute "distributor_id"
     */
    public function testPropertyDistributorId()
    {
    }

    /**
     * Test attribute "whitelist_path"
     */
    public function testPropertyWhitelistPath()
    {
    }

    /**
     * Test attribute "name"
     */
    public function testPropertyName()
    {
    }

    /**
     * Test attribute "user_inventory_id"
     */
    public function testPropertyUserInventoryId()
    {
    }

    /**
     * Test attribute "user_inventory_name"
     */
    public function testPropertyUserInventoryName()
    {
    }

    /**
     * Test attribute "user_inventory_type"
     */
    public function testPropertyUserInventoryType()
    {
    }

    /**
     * Test attribute "owner_inventory_id"
     */
    public function testPropertyOwnerInventoryId()
    {
    }

    /**
     * Test attribute "owner_inventory_name"
     */
    public function testPropertyOwnerInventoryName()
    {
    }

    /**
     * Test attribute "create_epoch_milli"
     */
    public function testPropertyCreateEpochMilli()
    {
    }

    /**
     * Test attribute "modify_epoch_milli"
     */
    public function testPropertyModifyEpochMilli()
    {
    }

    /**
     * Test attribute "parent_whitelist_id"
     */
    public function testPropertyParentWhitelistId()
    {
    }

    /**
     * Test attribute "parent_whitelist_name"
     */
    public function testPropertyParentWhitelistName()
    {
    }
}
