<?php
/**
 * ResponseSearchImsiSlotProfilesTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Distributor PPU Service
 *
 * © KnowRoaming LTD 2017
 *
 * OpenAPI spec version: v1.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.35
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

/**
 * ResponseSearchImsiSlotProfilesTest Class Doc Comment
 *
 * @category    Class
 * @description ResponseSearchImsiSlotProfiles
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class ResponseSearchImsiSlotProfilesTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "ResponseSearchImsiSlotProfiles"
     */
    public function testResponseSearchImsiSlotProfiles()
    {
    }

    /**
     * Test attribute "imsi_slot_profile_id"
     */
    public function testPropertyImsiSlotProfileId()
    {
    }

    /**
     * Test attribute "imsi_slot_profile_name"
     */
    public function testPropertyImsiSlotProfileName()
    {
    }

    /**
     * Test attribute "date_created_epoch"
     */
    public function testPropertyDateCreatedEpoch()
    {
    }

    /**
     * Test attribute "total_imsi_slot_profile_mappings"
     */
    public function testPropertyTotalImsiSlotProfileMappings()
    {
    }
}
