<?php
/**
 * ResponseInventoryStatusTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Distributor PPU Service
 *
 * © KnowRoaming LTD 2017
 *
 * OpenAPI spec version: v1.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.35
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

/**
 * ResponseInventoryStatusTest Class Doc Comment
 *
 * @category    Class
 * @description ResponseInventoryStatus
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class ResponseInventoryStatusTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "ResponseInventoryStatus"
     */
    public function testResponseInventoryStatus()
    {
    }

    /**
     * Test attribute "inventory_id"
     */
    public function testPropertyInventoryId()
    {
    }

    /**
     * Test attribute "network_access_stage"
     */
    public function testPropertyNetworkAccessStage()
    {
    }

    /**
     * Test attribute "rates_stage"
     */
    public function testPropertyRatesStage()
    {
    }

    /**
     * Test attribute "profile_stage"
     */
    public function testPropertyProfileStage()
    {
    }

    /**
     * Test attribute "inventory_profile_stage"
     */
    public function testPropertyInventoryProfileStage()
    {
    }

    /**
     * Test attribute "date_created"
     */
    public function testPropertyDateCreated()
    {
    }

    /**
     * Test attribute "date_modified"
     */
    public function testPropertyDateModified()
    {
    }
}
