<?php
/**
 * ResponseDataSessionTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Distributor PPU Service
 *
 * © KnowRoaming LTD 2017
 *
 * OpenAPI spec version: v1.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.35
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

/**
 * ResponseDataSessionTest Class Doc Comment
 *
 * @category    Class
 * @description ResponseDataSession
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class ResponseDataSessionTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "ResponseDataSession"
     */
    public function testResponseDataSession()
    {
    }

    /**
     * Test attribute "data_session_id"
     */
    public function testPropertyDataSessionId()
    {
    }

    /**
     * Test attribute "date_opened_in_utc"
     */
    public function testPropertyDateOpenedInUtc()
    {
    }

    /**
     * Test attribute "imsi_id"
     */
    public function testPropertyImsiId()
    {
    }

    /**
     * Test attribute "usage_in_kb"
     */
    public function testPropertyUsageInKb()
    {
    }

    /**
     * Test attribute "rat_type"
     */
    public function testPropertyRatType()
    {
    }

    /**
     * Test attribute "private_ip"
     */
    public function testPropertyPrivateIp()
    {
    }

    /**
     * Test attribute "public_ip"
     */
    public function testPropertyPublicIp()
    {
    }

    /**
     * Test attribute "apn"
     */
    public function testPropertyApn()
    {
    }

    /**
     * Test attribute "charge_type"
     */
    public function testPropertyChargeType()
    {
    }

    /**
     * Test attribute "country"
     */
    public function testPropertyCountry()
    {
    }

    /**
     * Test attribute "country_iso2_code"
     */
    public function testPropertyCountryIso2Code()
    {
    }

    /**
     * Test attribute "network"
     */
    public function testPropertyNetwork()
    {
    }
}
