<?php
/**
 * ResponseSearchTrafficPolicyTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Distributor PPU Service
 *
 * © KnowRoaming LTD 2017
 *
 * OpenAPI spec version: v1.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.35
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

/**
 * ResponseSearchTrafficPolicyTest Class Doc Comment
 *
 * @category    Class
 * @description ResponseSearchTrafficPolicy
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class ResponseSearchTrafficPolicyTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "ResponseSearchTrafficPolicy"
     */
    public function testResponseSearchTrafficPolicy()
    {
    }

    /**
     * Test attribute "traffic_policy_id"
     */
    public function testPropertyTrafficPolicyId()
    {
    }

    /**
     * Test attribute "network_plan_id"
     */
    public function testPropertyNetworkPlanId()
    {
    }

    /**
     * Test attribute "description"
     */
    public function testPropertyDescription()
    {
    }

    /**
     * Test attribute "epoch_created"
     */
    public function testPropertyEpochCreated()
    {
    }

    /**
     * Test attribute "epoch_modified"
     */
    public function testPropertyEpochModified()
    {
    }
}
