<?php
/**
 * SimNotificationApiTest
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Distributor PPU Service
 *
 * © KnowRoaming LTD 2017
 *
 * OpenAPI spec version: v1.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.35
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the endpoint.
 */

namespace Swagger\Client;

use Swagger\Client\Configuration;
use Swagger\Client\ApiException;
use Swagger\Client\ObjectSerializer;

/**
 * SimNotificationApiTest Class Doc Comment
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class SimNotificationApiTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test case for createSimNotification
     *
     * Create a Sim Notification entity.
     *
     */
    public function testCreateSimNotification()
    {
    }

    /**
     * Test case for getSimNotification
     *
     * Get a single Sim Notification.
     *
     */
    public function testGetSimNotification()
    {
    }

    /**
     * Test case for getSimNotifications
     *
     * Get a list of Sim Notifications.
     *
     */
    public function testGetSimNotifications()
    {
    }

    /**
     * Test case for updateSimNotification
     *
     * Update a Sim Notification entity.
     *
     */
    public function testUpdateSimNotification()
    {
    }
}
